import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=s=>document.querySelector(s),viewport=$('#view');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;viewport.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#252b30');const camera=new T.PerspectiveCamera(60,1,.001,10000);let controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
const root=new T.Group();scene.add(root);let groups=[],active,loaded=[],radius=1,center=new T.Vector3(),generation=0;const textures=new Map();
function resize(){const {width,height}=viewport.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize);
function clear(){root.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});root.clear()}
function resetControls(target){controls.dispose();controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.copy(target);controls.update()}
function photoView(index){const c=active?.cameras[index];if(!c)return;const r=c.rotation,q=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().set(...r[0],0,...r[1],0,...r[2],0,0,0,0,1));camera.position.set(...c.position);camera.up.set(0,1,0).applyQuaternion(q);camera.quaternion.copy(q);camera.fov=c.fov;const target=camera.position.clone().add(new T.Vector3(0,0,-c.targetDistance).applyQuaternion(q));camera.updateProjectionMatrix();resetControls(target)}
function overview(){camera.up.set(0,1,0);camera.fov=60;camera.position.copy(center).add(new T.Vector3(.7,.4,1).normalize().multiplyScalar(radius/Math.min(1,camera.aspect)));camera.updateProjectionMatrix();resetControls(center)}
function renderData(){clear();const only=$('#surface').value,supported=$('#supported').checked;let count=0,faces=0,recoveredCount=0;const recover=$('#recover').checked;
 loaded.forEach((data,i)=>{if(only!=='all'&&Number(only)!==i)return;const keep=data.valid.map((v,k)=>(v||(recover&&data.recovered?.[k]))&&(!supported||data.support[k]>=2));recoveredCount+=keep.filter((v,k)=>v&&!data.valid[k]).length;const geo=new T.BufferGeometry();
 if($('#mode').value==='surface'){
  geo.setAttribute('position',new T.Float32BufferAttribute(data.positions.flat(),3));const uv=[],cols=Math.ceil(active.width/2);for(let k=0;k<data.positions.length;k++)uv.push(((k%cols)*2+.5)/active.width,1-(Math.floor(k/cols)*2+.5)/active.height);geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));
  const indices=[];for(let j=0;j<data.indices.length;j+=3){const tri=data.indices.slice(j,j+3);if(tri.every(k=>keep[k]))indices.push(...tri)}geo.setIndex(indices);root.add(new T.Mesh(geo,new T.MeshBasicMaterial({map:textures.get(active.photos[i]),side:T.DoubleSide})));faces+=indices.length/3;
 }else{const positions=[],colors=[];data.positions.forEach((p,k)=>{if(!keep[k])return;positions.push(...p);const c=new T.Color().setRGB(...data.colors[k].map(x=>x/255),T.SRGBColorSpace);colors.push(c.r,c.g,c.b)});geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));root.add(new T.Points(geo,new T.PointsMaterial({vertexColors:true,size:2,sizeAttenuation:false})))}count+=keep.filter(Boolean).length;
 });
 $('#status').textContent=`${active.photos.length} 张照片参与预测\n当前 ${count.toLocaleString()} 个采样点 / ${faces.toLocaleString()} 个三角面\n其中恢复 ${recoveredCount.toLocaleString()} 个连续表面采样点\n有效像素中 ${Math.round(active.consistent_pixels/active.valid_pixels*100)}% 有跨视角深度支持\n这是学习型估计，不是已验证的完整场景。`;
}
async function load(){const token=++generation;$('#status').textContent='正在载入预测表面…';active=groups[Number($('#group').value)];if(!active)return;
 const local=active;const data=await Promise.all(local.surfaces.map(s=>fetch('/neural-results/'+s.file).then(r=>{if(!r.ok)throw Error('缺少表面数据');return r.json()})));
 for(const name of local.photos){if(!textures.has(name)){const texture=await new T.TextureLoader().loadAsync('/home-photos/'+name);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures.set(name,texture)}}
 if(token!==generation)return;loaded=data;for(const id of ['#surface','#camera'])$(id).replaceChildren();const all=document.createElement('option');all.value='all';all.textContent='合并所有照片的预测表面';$('#surface').append(all);
 local.photos.forEach((name,i)=>{for(const id of ['#surface','#camera']){const option=document.createElement('option');option.value=i;option.textContent=`${i+1} · ${name.split('/').at(-1)}`;$(id).append(option)}});
 const valid=[];data.forEach(d=>d.positions.forEach((p,i)=>{if(d.valid[i])valid.push(p)}));const axes=[0,1,2].map(k=>valid.map(p=>p[k]).sort((a,b)=>a-b));const lo=new T.Vector3(...axes.map(a=>a[Math.floor(a.length*.03)])),hi=new T.Vector3(...axes.map(a=>a[Math.floor(a.length*.97)]));center.copy(lo).add(hi).multiplyScalar(.5);radius=Math.max(lo.distanceTo(hi),.01);camera.near=radius/10000;camera.far=radius*100;
 renderData();overview();
}
for(const id of ['#surface','#mode','#supported','#recover'])$(id).onchange=renderData;$('#camera').onchange=()=>photoView(Number($('#camera').value));$('#overview').onclick=overview;$('#group').onchange=()=>load().catch(e=>$('#error').textContent=e.message);
const keys=new Set();addEventListener('keydown',e=>{if(e.target.closest('input,select,button'))return;if('wasdqe'.includes(e.key.toLowerCase())){keys.add(e.key.toLowerCase());e.preventDefault()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());let previous=performance.now();
renderer.setAnimationLoop(now=>{const dt=Math.min((now-previous)/1000,.05);previous=now;if(keys.size){const direction=new T.Vector3((keys.has('d')?1:0)-(keys.has('a')?1:0),(keys.has('e')?1:0)-(keys.has('q')?1:0),(keys.has('s')?1:0)-(keys.has('w')?1:0)).normalize().applyQuaternion(camera.quaternion).multiplyScalar(radius*.12*dt);camera.position.add(direction);controls.target.add(direction)}controls.update();renderer.render(scene,camera)});
try{const r=await fetch('/neural-results/manifest.json');if(!r.ok)throw Error('预测尚未完成');groups=await r.json();if(!groups.length)throw Error('没有可显示的预测');groups.forEach((g,i)=>{const option=document.createElement('option');option.value=i;option.textContent=({main:'正房与小棚',west:'西厢房与大门',yard:'院内与大门',all:'九张场景照片联合预测'}[g.group]||g.group);$('#group').append(option)});await load()}catch(e){$('#error').textContent=e.message;$('#status').textContent='尚无可显示的结果'}
